# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-06 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='pincode',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
