# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-27 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170411_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='apartment',
            field=models.CharField(max_length=50, verbose_name='Flat No./Bldg. No., Apartment'),
        ),
    ]
